# .circleci/config.yml
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# Insoired by: https://medium.com/uptech-team/swift-package-manager-and-how-to-cache-it-with-ci-14968cd58c5f
version: 2.1
orbs:
  macos: circleci/macos@2
  
jobs:
  build-and-test:
    macos:
      xcode: 15.3.0
    #parallelism: 2  Does not work of open source macOS
    resource_class: macos.m1.medium.gen1
    working_directory: ~/litewallet-ios/
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: all_unit_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: "Initialize submodule(s)"  
          command: "git submodule init && git submodule update --init --recursive"
      - run:
          name: "Setup env files"
          command: |
            echo 'export $GOOGLE_SERVICES_PLIST="$GOOGLE_SERVICES_PLIST"' >> $BASH_ENV
            echo "$GOOGLE_SERVICES_PLIST" | base64 --decode > litewallet/GoogleService-Info.plist
            echo 'export $REMOTE_CONFIG_DEFAULTS="$REMOTE_CONFIG_DEFAULTS"' >> $BASH_ENV
            echo "$REMOTE_CONFIG_DEFAULTS" | base64 --decode > litewallet/remote-config-defaults.plist
            echo 'export $DEBUG_PARTNER_KEYS="$DEBUG_PARTNER_KEYS"' >> $BASH_ENV
            echo "$DEBUG_PARTNER_KEYS" | base64 --decode > litewallet/partner-keys.plist
      - restore_cache:
          name: Restore SPM Cache
          keys:
            - spm-cache-{{ checksum "Package.resolved" }}
      - run: 
          name: Install Bundler
          command: gem install bundler:1.17.2; bundle update --bundler; bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - save_cache:
          name: Save SPM Cache
          key: spm-cache-{{ checksum "Package.resolved" }}
          paths:
            - SourcePackages/
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: 14.0.1
    working_directory: ~/litewallet-ios/
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: cd ios; bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/litewallet.ipa

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
      - beta:
          filters:
            branches:
              only: develop
          requires:
            - build-and-test